// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// 命令（cmd_command）。
type Command struct {
	ID           string    `json:"id"`
	Type         string    `json:"type"`
	State        string    `json:"state"`
	ScheduledFor time.Time `json:"scheduledFor"`
}

type Mutation struct {
}

type Query struct {
}

// keyset ページングの1ページ。first は必須で、サーバ側で上限を掛ける（DoS 対策・EXP-24）。
type RobotConnection struct {
	Robots    []Robot `json:"robots"`
	EndCursor *string `json:"endCursor,omitempty"`
	HasNext   bool    `json:"hasNext"`
}

// 命令送信の入力。冪等キーは必須（二重発行を防ぐ・EXP-27）。
type SendCommandInput struct {
	RobotID        string  `json:"robotId"`
	Type           string  `json:"type"`
	Payload        *string `json:"payload,omitempty"`
	IdempotencyKey string  `json:"idempotencyKey"`
}

type Subscription struct {
}

// ロボットの状態。文字列でなく列挙（model.Status に対応）。
type RobotStatus string

const (
	RobotStatusUnknown RobotStatus = "UNKNOWN"
	RobotStatusIdle    RobotStatus = "IDLE"
	RobotStatusRunning RobotStatus = "RUNNING"
	RobotStatusError   RobotStatus = "ERROR"
	RobotStatusOffline RobotStatus = "OFFLINE"
)

var AllRobotStatus = []RobotStatus{
	RobotStatusUnknown,
	RobotStatusIdle,
	RobotStatusRunning,
	RobotStatusError,
	RobotStatusOffline,
}

func (e RobotStatus) IsValid() bool {
	switch e {
	case RobotStatusUnknown, RobotStatusIdle, RobotStatusRunning, RobotStatusError, RobotStatusOffline:
		return true
	}
	return false
}

func (e RobotStatus) String() string {
	return string(e)
}

func (e *RobotStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RobotStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RobotStatus", str)
	}
	return nil
}

func (e RobotStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RobotStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RobotStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// テナント内のロール。VIEWER < OPERATOR < ADMIN の順で強い。
type Role string

const (
	RoleViewer   Role = "VIEWER"
	RoleOperator Role = "OPERATOR"
	RoleAdmin    Role = "ADMIN"
)

var AllRole = []Role{
	RoleViewer,
	RoleOperator,
	RoleAdmin,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleViewer, RoleOperator, RoleAdmin:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
