package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/aq35/sample_manual/internal/repo"
)

// Name is the resolver for the name field.
//
// 射影（EXP-19/21）: name は別表 robot_profile。要求されたときだけ引く。
// 一覧で name を要求しなければ、この解決関数は呼ばれず profile を触らない。
func (r *robotResolver) Name(ctx context.Context, obj *Robot) (string, error) {
	sc, err := r.scope(ctx)
	if err != nil {
		return "", err
	}
	return nameOf(ctx, sc, obj.ID)
}

// Commands is the resolver for the commands field.
//
// N+1 の温床（EXP-23）: ロボットごとに呼ばれる。ローダがあればバッチ（1クエリ）、
// 無ければ素朴に1台ずつ引く（N+1）。実験でこの差を測る。
func (r *robotResolver) Commands(ctx context.Context, obj *Robot, first *int) ([]Command, error) {
	sc, err := r.scope(ctx)
	if err != nil {
		return nil, err
	}
	n := 20
	if first != nil {
		n = *first
	}
	if n > loaderMax {
		n = loaderMax
	}
	if l, ok := loadersFrom(ctx); ok {
		cmds, err := l.Commands.Load(ctx, obj.ID) // バッチに参加（1クエリに畳まれる）
		if err != nil {
			return nil, err
		}
		if len(cmds) > n {
			cmds = cmds[:n]
		}
		return cmds, nil
	}
	return commandsForRobot(ctx, sc, obj.ID, n) // ローダ無し＝N+1
}

// Robots is the resolver for the robots field.
func (r *queryResolver) Robots(ctx context.Context, first int, after *string) (*RobotConnection, error) {
	sc, err := r.scope(ctx)
	if err != nil {
		return nil, err
	}
	if first < 1 {
		first = 1
	}
	if first > r.maxPage() { // 無制限一覧を作らせない
		first = r.maxPage()
	}
	cursor := ""
	if after != nil {
		cursor = *after
	}
	// hasNext 判定のため1件多めに引く
	robots, err := listRobots(ctx, sc, cursor, first+1)
	if err != nil {
		return nil, err
	}
	conn := &RobotConnection{}
	if len(robots) > first {
		conn.HasNext = true
		robots = robots[:first]
	}
	conn.Robots = robots
	if len(robots) > 0 {
		last := robots[len(robots)-1].ID
		conn.EndCursor = &last
	}
	return conn, nil
}

// Robot is the resolver for the robot field.
//
// テナント分離（EXP-24）: 他テナントの id を渡されても、:tenant で弾かれ null になる。
func (r *queryResolver) Robot(ctx context.Context, id string) (*Robot, error) {
	sc, err := r.scope(ctx)
	if err != nil {
		return nil, err
	}
	return getRobot(ctx, sc, id)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Robot returns RobotResolver implementation.
func (r *Resolver) Robot() RobotResolver { return &robotResolver{r} }

type queryResolver struct{ *Resolver }
type robotResolver struct{ *Resolver }

// scope は context の検証済みテナントから Scope を作る。ここが全リゾルバの DB 入口。
func (r *Resolver) scope(ctx context.Context) (*repo.Scope, error) {
	t, err := tenantFrom(ctx)
	if err != nil {
		return nil, err
	}
	return r.DB.Tenant(t), nil
}
