package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
)

// SendCommand is the resolver for the sendCommand field.
//
// 書き込みの順序: 入力検証（EXP-27）→ 行レベル認可（EXP-28）→ 冪等な発行（EXP-27）。
func (r *mutationResolver) SendCommand(ctx context.Context, input SendCommandInput) (*Command, error) {
	// ① 入力検証（DB に触れる前に、クライアント起因のエラーとして弾く）
	if err := validateSendCommand(input); err != nil {
		return nil, err
	}
	sc, err := r.scope(ctx)
	if err != nil {
		return nil, err
	}
	// ② 行レベル認可: この主体が、この robot を操作してよいか
	principal, ok := principalFrom(ctx)
	if !ok {
		return nil, ErrNoTenant // 主体不明（未認証）
	}
	allowed, err := canOperate(ctx, sc, principal, input.RobotID)
	if err != nil {
		return nil, err
	}
	if !allowed {
		return nil, userErr("forbidden: この robot を操作する権限がない")
	}
	// ③ 冪等な発行（同じ idempotencyKey の再送は既存を返す）
	return sendCommand(ctx, sc, input)
}

// Robots is the resolver for the robots field.
func (r *queryResolver) Robots(ctx context.Context, first int, after *string) (*RobotConnection, error) {
	sc, err := r.scope(ctx)
	if err != nil {
		return nil, err
	}
	if first < 1 {
		first = 1
	}
	if first > r.maxPage() { // 無制限一覧を作らせない
		first = r.maxPage()
	}
	cursor := ""
	if after != nil {
		cursor = *after
	}
	// hasNext 判定のため1件多めに引く
	robots, err := listRobots(ctx, sc, cursor, first+1)
	if err != nil {
		return nil, err
	}
	conn := &RobotConnection{}
	if len(robots) > first {
		conn.HasNext = true
		robots = robots[:first]
	}
	conn.Robots = robots
	if len(robots) > 0 {
		last := robots[len(robots)-1].ID
		conn.EndCursor = &last
	}
	return conn, nil
}

// Robot is the resolver for the robot field.
//
// テナント分離（EXP-24）: 他テナントの id を渡されても、:tenant で弾かれ null になる。
func (r *queryResolver) Robot(ctx context.Context, id string) (*Robot, error) {
	sc, err := r.scope(ctx)
	if err != nil {
		return nil, err
	}
	return getRobot(ctx, sc, id)
}

// Name is the resolver for the name field.
//
// 射影（EXP-19/21）: name は別表 robot_profile。要求されたときだけ引く。
// 一覧で name を要求しなければ、この解決関数は呼ばれず profile を触らない。
func (r *robotResolver) Name(ctx context.Context, obj *Robot) (string, error) {
	sc, err := r.scope(ctx)
	if err != nil {
		return "", err
	}
	return nameOf(ctx, sc, obj.ID)
}

// Serial is the resolver for the serial field.
//
// 認可（EXP-25）: このフィールドは @auth(requires: ADMIN)。@auth ディレクティブが
// この解決関数の「前に」ロールを検査するので、ここに来る時点で ADMIN は保証済み。
// 値自体は別表 robot_profile から引く。
func (r *robotResolver) Serial(ctx context.Context, obj *Robot) (*string, error) {
	sc, err := r.scope(ctx)
	if err != nil {
		return nil, err
	}
	s, err := serialOf(ctx, sc, obj.ID)
	if err != nil {
		return nil, err
	}
	return &s, nil
}

// Commands is the resolver for the commands field.
//
// N+1 の温床（EXP-23）: ロボットごとに呼ばれる。ローダがあればバッチ（1クエリ）、
// 無ければ素朴に1台ずつ引く（N+1）。実験でこの差を測る。
func (r *robotResolver) Commands(ctx context.Context, obj *Robot, first *int) ([]Command, error) {
	sc, err := r.scope(ctx)
	if err != nil {
		return nil, err
	}
	n := 20
	if first != nil {
		n = *first
	}
	if n > loaderMax {
		n = loaderMax
	}
	if l, ok := loadersFrom(ctx); ok {
		cmds, err := l.Commands.Load(ctx, obj.ID) // バッチに参加（1クエリに畳まれる）
		if err != nil {
			return nil, err
		}
		if len(cmds) > n {
			cmds = cmds[:n]
		}
		return cmds, nil
	}
	return commandsForRobot(ctx, sc, obj.ID, n) // ローダ無し＝N+1
}

// RobotVersion is the resolver for the robotVersion field.
//
// gqlgen のサブスクリプションは「チャネルを返す」だけ。接続ごとに DB を引かず、テナント単位の
// hub（ssehub.Registry）に相乗りする（EXP-38/39）。ctx が切れたら購読解除する（漏れ防止）。
func (r *subscriptionResolver) RobotVersion(ctx context.Context) (<-chan int, error) {
	t, err := tenantFrom(ctx)
	if err != nil {
		return nil, err
	}
	if r.Events == nil {
		return nil, userErr("subscription unavailable")
	}
	src, initial, release := r.Events.Subscribe(string(t))
	out := make(chan int, 1)
	go func() {
		defer release() // 切断で hub から購読解除（最後の1人なら poller も止まる）
		defer close(out)
		if initial >= 0 {
			select {
			case out <- int(initial): // 初期スナップショット（hub キャッシュ。DB は引かない）
			case <-ctx.Done():
				return
			}
		}
		for {
			select {
			case v := <-src:
				select {
				case out <- int(v):
				case <-ctx.Done():
					return
				}
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Robot returns RobotResolver implementation.
func (r *Resolver) Robot() RobotResolver { return &robotResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	robotResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
